export enum Frame {
  Original = '1993',
  Updated = '1997',
  Modern = '2003',
  HolofoilStamp = '2015',
  Future = 'future',
}

export enum FrameEffect {
  Legendary = 'legendary',
  Miracle = 'miracle',
  Enchantment = 'enchantment',
  Draft = 'draft',
  Devoid = 'devoid',
  Tombstone = 'tombstone',
  Colorshifted = 'colorshifted',
  Inverted = 'inverted',
  SunMoonDfc = 'sunmoondfc',
  CompassLandDfc = 'compasslanddfc',
  OriginPwDfc = 'originpwdfc',
  MoonEldraziDfc = 'mooneldrazidfc',
  WaxingAndWaningMoonDfc = 'waxingandwaningmoondfc',
  Showcase = 'showcase',
  ExtendedArt = 'extendedart',
  Companion = 'companion',
  Etched = 'etched',
  Snow = 'snow',
  Lesson = 'lesson',
  ShatteredGlass = 'shatteredglass',
  ConvertDfc = 'convertdfc',
  FanDfc = 'fandfc',
  UpsideDownDfc = 'upsidedowndfc',
  Spree = 'spree',
}
