export enum ScryfallLanguage {
  English = 'en',
  Spanish = 'es',
  French = 'fr',
  German = 'de',
  Italian = 'it',
  Portuguese = 'pt',
  Japanese = 'ja',
  Korean = 'ko',
  Russian = 'ru',
  SimplifiedChinese = 'zhs',
  TraditionalChinese = 'zht',
  Hebrew = 'he',
  Latin = 'la',
  AncientGreek = 'grc',
  Arabic = 'ar',
  Sanskrit = 'sa',
  Phyrexian = 'ph',
  Quenya = 'qya',
}
